---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: running-job-
spec:
  template:
    spec:
      serviceAccountName: hibernator
      containers:
      - name: worker
        image: quay.io/jpacker/hibernation-curator:latest
        imagePullPolicy: Always
        command: ['./action']
        env:
        - name: TAKE_ACTION
          value: Running
      restartPolicy: OnFailure